//display actions
export const TOGGLE_LOGIN_POPUP = 'TOGGLE_LOGIN_POPUP';
export const TOGGLE_QUESTION_POPUP = 'TOGGLE_QUESTION_POPUP';

//question actions
export const REQUEST_FETCH_QUESTION = 'REQUEST_FETCH_QUESTION';
export const RECEIVE_FETCH_QUESTION = 'RECEIVE_FETCH_QUESTION';
export const REQUEST_ADD_QUESTION = 'REQUEST_ADD_QUESTION';
export const RECEIVE_ADD_QUESTION = 'RECEIVE_ADD_QUESTION';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const HOVER_OVER_QUESTION = 'HOVER_OVER_QUESTION';
export const TOGGLE_IS_ADDING_QUESTION = 'TOGGLE_IS_ADDING_QUESTION';
export const SET_QUESTION_TO_VIEW = 'SET_QUESTION_TO_VIEW';

//answer actions
export const REQUEST_FETCH_ANSWER = 'REQUEST_FETCH_ANSWER';
export const RECEIVE_FETCH_ANSWER = 'RECEIVE_FETCH_ANSWER';
export const FETCH_ANSWER = 'FETCH_ANSWER';
export const REQUEST_ADD_ANSWER = 'REQUEST_ADD_ANSWER';
export const RECEIVE_ADD_ANSWER = 'RECEIVE_ADD_ANSWER';
export const ADD_ANSWER = 'ADD_ANSWER';

//tag actions
export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS';
export const REQUEST_FETCH_ALL_TAGS = 'REQUEST_FETCH_ALL_TAGS';
export const RECEIVE_FETCH_ALL_TAGS = 'RECEIVE_FETCH_ALL_TAGS';

//accountActions
export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';

export const SIGN_UP_ACCOUNT_REQUESTED = 'SIGN_UP_ACCOUNT_REQUESTED';
export const SIGN_UP_ACCOUNT_SUCCESS = 'SIGN_UP_ACCOUNT_SUCCESS';
export const SIGN_UP_ACCOUNT_FAIL = 'SIGN_UP_ACCOUNT_FAIL';

export const REGISTER_ACCOUNT_REQUESTED = 'REGISTER_ACCOUNT_REQUESTED';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL = 'REGISTER_ACCOUNT_FAIL';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

//formActions
export const FORM_VALIDATE = 'FORM_VALIDATE';
export const FORM_ASYNC_VALIDATE_REQUESTED = 'FORM_ASYNC_VALIDATE_REQUESTED';
export const FORM_ASYNC_VALIDATE_RECEIVED = 'FORM_ASYNC_VALIDATE_RECEIVED';
export const FORM_ASYNC_VALIDATE_RESET = 'FORM_ASYNC_VALIDATE_RESET';
export const FORM_ON_CHANGE = 'FORM_ON_CHANGE';
export const FORM_ON_BLUR = 'FORM_ON_BLUR';
export const FORM_RESET_FIELD = 'FORM_RESET_FIELD';
